version: 2
jobs:
  build:
    working_directory: ~/react-simple-step-wizard
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Validate lockfile
          command: npm run lockfile-lint
      - restore_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: Run Tests
          command: npm test
